apisix:
  node_listen: 9080
  enable_ipv6: false

plugins:
  - cors
  - openid-connect
  - opa
  - proxy-rewrite
  - serverless-pre-function
  - serverless-post-function
  - umzh-role-check

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
